version: "3"


services:
  nginx:
    image: nginx:1.23-alpine
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1448:80
    networks:
      - app_vnv
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - 8081:5000
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - msql
    networks:
      - app_vnv



  msql:
    image: mysql:latest
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cursor_dbx
    volumes:
      - ./docker/db:/var/lib/mysql
    networks:
      - app_vnv


networks:
  app_vnv:
    driver: bridge