# Generated by Django 4.2.1 on 2023-05-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_slide"),
    ]

    operations = [
        migrations.AddField(
            model_name="slide",
            name="is_first_slide",
            field=models.BooleanField(default=False),
        ),
    ]
